import styles from './contact.module.css';
import Image from 'next/image';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
  };

const Contact = () =>{
    return(
        <div className={styles.container}>
            <div className={styles.imgContainer}>
                <Image src="/contact.png" alt=''fill className={styles.img}/>
            </div>
            <div className={styles.formContainer}>
                <form action='' className={styles.form}>
                    <input type='text' placeholder='Name and Surname' />
                    <input type='email' placeholder='Email address' />
                    <input type='text' placeholder='phone number' />

                    <textarea placeholder='Message'></textarea>
                    <button type='submit'>Send</button> 
                </form>
            </div>
        </div>
    )
}
export default Contact;